### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by balaji-marist** [dblossom-marist/PerfMon#10]
GUI take a long time to load the initial screen with all process from all users.

**Comment by dblossom-marist** [comment]
If using Processes.py from master branch I suspect this line of code causing issue.

cpuPercent = pid.cpu_percent(interval=0.1)

**Comment by dblossom-marist** [comment]
Seems to be better after lowering interval to .00001 as @balaji-marist suggested, however, that's just a temp fix. Need to come back to this and find best way to collect CPU percentage per process.

**Comment by balaji-marist** [comment]
changes seems to have made the app stable.
