### ISSUE TITLE
cpu count

### ISSUE THREAD

**Issue by balaji-marist** [dblossom-marist/PerfMon#21]
We need a function in cpu.py that will return the physical CPU count, something like getCpuCount()

Thanks

**Comment by dblossom-marist** [comment]
Created function `getCpuCount(bool)` as shown below:

Passing True will return logical CPUs while False or nothing will return physical cores.
```
def getCpuCount(self, logicalCpuCount = False):
    if isinstance(logicalCpuCount, bool):
        return psutil.cpu_count(logical = logicalCpuCount)
```

**Test:**
```
c = Cpu()
print(c.getCpuCount())
print(c.getCpuCount(True))
print(c.getCpuCount(False))
print(c.getCpuCount("bad data"))
```
**Output of test:***
```
6
12
6
None
```

**Comment by balaji-marist** [comment]
Thanks, looks good
