### ISSUE TITLE
cpu.py

### ISSUE THREAD

**Issue by balaji-marist** [dblossom-marist/PerfMon#25]
please remove the print statements in cpu.py

**Comment by dblossom-marist** [comment]
While I did have a few debug print statements in my local branch, I do not see any print statements **AFTER** I just merged my changes into master branch. I suspect you're talking about the below code which was before my merge/pull into master request.
https://github.com/dblossom-marist/PerfMon/blob/b46bce2ebdc8ef0be6219d0052efb3b5f3c0b4b5/Cpu.py
```
def __init__(self):
    logicalCPUs = psutil.cpu_count(logical = True)
    physicalCPUSs = psutil.cpu_count(logical = False)
    print("Logical CPUS: " + str(logicalCPUs))
    print("Physical CPUS: " + str(physicalCPUSs))
```
**The file now looks like:**
https://github.com/dblossom-marist/PerfMon/blob/master/Cpu.py
```
def __init__(self):
    pass
```

**Comment by dblossom-marist** [comment]
Note: got a bit trigger happy with labels. It is valid as the print statements were there in the master branch, just not updated from my local changes (if my suspicions above are true) and of course I'd fix it :)

**Comment by balaji-marist** [comment]
Thanks
