### ISSUE TITLE
database.py

### ISSUE THREAD

**Issue by balaji-marist** [dblossom-marist/PerfMon#47]
When checking for next hour and constructing the time object in line 259 and 262, it adds an extra zero to hour greater than 9.

**Comment by dblossom-marist** [comment]
Line 259 should be okay, only will enter that code for a roll over test... meaning the hour is midnight which should = 00.

However, lines 262 & 365 needed to be adjusted... Actually the `if` statement prior should check for *<10* not *<12*.

Fixed issues two commits ago, closing.
